### PR TITLE
add python3.9 to workflow matrices

### PR DESCRIPTION
**Pull request by skarzi**
Run tests against python 3.9

### CODE REVIEW

**Comment by skarzi** [comment]
This PR is `draft` because we need to wait until `UsePythonVersion` will support Python 3.9

**Comment by skarzi** [comment]
`UsePythonVersion` supports python 3.9 now, but there are still failing tests

**Comment by skarzi** [comment]
[`test.integration.test_ipydb.test_report`](https://github.com/tonybaloney/wily/blob/a04e531b90e9a36c04d4061572d2461f6bc8a414/test/integration/test_ipynb.py#L32) is failing, because `Harvester`s defined in [`radon.cli.harvest`](https://github.com/rubik/radon/blob/0a6aff726f29abfe1547b27446f3b2d78d2d77e6/radon/cli/harvest.py#L1) module doesn't collect any metrics for `ipydb` files when code is ran with python 3.9

But according to [`radon` `README.md`](https://github.com/rubik/radon), it doesn't officially support Python 3.9:

> Radon will run from Python 2.7 to Python 3.8 (except Python versions from 3.0 to 3.3)

**Comment by tonybaloney** [comment]
thanks @skarzi

**Pull request merged**
