### PR TITLE
Patch aggregate statistics

### PR DESCRIPTION
**Pull request by ThomasTNO**
I discovered that the aggregated statistics were not properly computed.

In particular in case of file movements, file deletions and deeply nested directories.

This PR should resolve the issue. Please validate if this does not break other functionality (as I am relatively new to the code base.)

### CODE REVIEW

**Comment by ThomasTNO** [comment]
I fixed most unit tests, two failing tests remaining. Feel free to suggest a solution to those.

**Comment by tonybaloney** [comment]
Thanks for this! Since this changes the wily cache spec, have you tested what happens when you have a cache built with an older version?

**Comment by ThomasTNO** [comment]
> Thanks for this! Since this changes the wily cache spec, have you tested what happens when you have a cache built with an older version?

I did not test this. I guess that fails, as the `Revision()` variables changed. Anyhow, my suggestion would be to rebuild the cache as the previous aggregates were faulty.

**Comment by ThomasTNO** [comment]
I just ran it on cache built with an older version, it seems to just work fine.

**Pull request merged**
