### PR TITLE
refactor: improve CI and local development

### PR DESCRIPTION
**Pull request by skarzi**
This PR is quite big and changes several things:

+ fix main deps declaration  https://github.com/tonybaloney/wily/commit/52c86c5083addcb71371cdc6efc901ecf5711326
+ declare dev and test deps in `pyproject.toml` using flit extras
+ add dev/test tools configuration to proper config files
+ add linting and testing stages to `Makefile`
+ removes tox support (`flit` and `Makefile` should be used for local development)
+ merges `main` and `lint_python` workflows

Things to do (but probably in separate PRs):

- [x] add better coverage configuration - @skarzi 
- [x] investigate why tests fail and fix them
- [x] add [`.editorconfig`](https://editorconfig.org/) and clean whitespaces in the codebase - check #158
- [ ] update `.gitignore` (e.g. with `wily_report` and `foo`)
- [ ] move codecov token to secrets - @tonybaloney 
- [ ] set proper `black` configuration, apply it on the codebase and require it in `Makefile`
- [ ] set proper `isort` configuration, apply it on the codebase and require it in `Makefile`
- [ ] resolve flake8 issues and clean `ignore` in its config and set its proper configuration
- [ ] set proper `codespell` configuration, apply it on the codebase and require it in `Makefile`
- [ ] set proper `mypy` configuration, resolve its issues and require it in `Makefile`
- [ ] add some useful `pytest` plugins, like `pytest-timeout` or `pytest-randomly`

### CODE REVIEW

**Comment by skarzi** [comment]
I don't know why tests run on windows are failing, if you have any idea please share!

**Comment by tonybaloney** [comment]
There's a lot going on in this PR making it really hard to review. Could you please cherry-pick these commits into [atomic changes](https://fagnerbrack.com/one-pull-request-one-concern-e84a27dfe9f1) i.e. one pull-request = one concern

**Comment by skarzi** [comment]
Yes, there is a log going on in this PR, but I have made atomic changes on the commit level, so you can review one commit after another. However, if it's still hard to review let me know and I will try to split it into multiple PRs with atomic changes ;)

**Comment by tonybaloney** [comment]
1 test is failing on Windows:

```
FAILED test/integration/test_complex_commits.py::test_skip_files
```

**Comment by skarzi** [comment]
Yes, but unfortunately, I don't know why it's failing at first sight and I don't have access to a windows machine so I can dig into this test more deeply. 
It seems like for some reason the `src\\test1.py` is not included in the final report data.

**Comment by skarzi** [comment]
But this test is also failing on the main branch, let's check it [here](https://github.com/tonybaloney/wily/runs/7422527148?check_suite_focus=true#step:5:68)

**Comment by tonybaloney** [comment]
Ok. I have a windows machine, will test on that and make sure it's unrelated so we can merge this 👍🏻

**Pull request merged**
