### PR TITLE
Adds support for aggregated graphs + patch title

### PR DESCRIPTION
**Pull request by ThomasTNO**
This pull request implements aggregated graph support for directories.

It also patches a bug in title creation.

### CODE REVIEW

**Comment by tonybaloney** [comment]
Thanks! Please can you add a basic test in https://github.com/tonybaloney/wily/blob/master/test/integration/test_graph.py

**Comment by ThomasTNO** [comment]
> Thanks! Please can you add a basic test in https://github.com/tonybaloney/wily/blob/master/test/integration/test_graph.py

Added two basic tests

**Comment by ThomasTNO** [comment]
Attempted to patch the labels of data points, but it still seems bugged.

**Comment by ThomasTNO** [comment]
> Attempted to patch the labels of data points, but it still seems bugged.

Should be working properly now.

**Pull request merged**
